### PR TITLE
Add subtitle support and cleaner sets

### PR DESCRIPTION
**Pull request by glitch452**
1. Suport for local subtitle files.  Naming conventions of both Plex and XBMC/Kodi accepted.
2. Add settings to enable subtitle support and a global subtitle folder
3. Remove 'Series' and 'Collection' from the end of a movie set name since Plex adds 'Collection' in the GUI already

### CODE REVIEW

**Comment by SlrG** [comment]
Cool. You are very quick. :) And you did as I hoped you would, by putting everything in a separate module. Looks fine so far. I had not yet the time to test it. But I guess you did that and it works fine? Just asking, because I have trustingly merged pull requests before, only to notice afterwards the submitter did not even test his code. ^_^

**Comment by glitch452** [comment]
:) Yeah... I sort of got obsessed for a few days.  Once I got through the Python and Plex API learning curves, and figured out how to test, the actual coding was pretty quick.  Figuring out the whole process of forking and pull requests on here took some learning too.  

As for testing... Yes and No.  I re-imported my whole movie library with this fork, and it worked wonderfully.  However, I only have .srt subtitle files in my library so I haven't tested other formats.  Most are handled similarly; the big difference would be the vobsub format with the .sub and .idx files.  So... hopefully you have some of those that you can test with?  Also, the collection tweak works beautifully; I no longer have "<set name> collection collection" in my library :)

I was wondering about the whole separate module thing since the rest of this project is all in one file, but I figured it was cleaner to separate it so... Im glad you approve!  If there are any other etiquette things you had in mind, let me know and I can update the code.  I haven't updated the version number.  I figured you would want to test and then do that yourself?

I was also considering changing the settings a little too.  Specifically, instead of the disable local media support option, have separate options that are handled individually to enable Posters, Fanart, Trailers, and Subtitles.  My concern was how the change would be handled for users upgrading their existing version.  If they didn't know that the settings were tweaked, they could get unexpected results on their next import.  What do you think?  How have you handled that sort of thing in the past?

**Comment by SlrG** [comment]
Sadly I get the following exception:
```
2017-09-14 12:21:16,831 (2af994e06700) :  CRITICAL (agentkit:1078) - Exception in the update function of agent named 'XBMCnfoMoviesImporter', called with guid 'com.plexapp.agents.xbmcnfo://tt0267804?lang=xn' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-d07c1f408/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1076, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/XBMCnfoMoviesImporter.bundle/Contents/Code/__init__.py", line 809, in update
    subtitle_files.extend(subtitles.process_subtitle_files(part))
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/XBMCnfoMoviesImporter.bundle/Contents/Code/subtitles.py", line 25, in process_subtitle_files
    if os.path.isdir(preferences['subglobalpath']):
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
Probably happens, because I have no global subtitle path entered?

**Comment by SlrG** [comment]
As for the separate options to enable Posters, Fanart, Trailers, and Subtitles, I don't quite see the benefit? If local media assets is enabled, it will fetch all of those. Does it make sense, to have the agent pull duplicates?

It would make sense if e.g. it were possible to disable posters in local media assets and enable it in the agent, while leaving everything else to local media assets. But as this is and probably never will be possible, what sense does it make?

Or am I missing something?

**Comment by glitch452** [comment]
Yes, sorry, I incorrectly assumed that the isdir() function would handle an empty folder.  I've updated that and I'll submit a new pull request.  

For the options.  Yes, for the general case, I believe you are correct... Ideally, someone would only use the local media agent or the local assets form this agent.  However, I was thinking that it would give the end user more control over which assets are imported.  For instance, in my case, I would have been able to import the posters only from this agent and use the local media agent for the rest since my poster naming convention is supported by XBMC/Kodi but not Plex.  Separating the option for posters vs. fanart would eliminate the duplicate fanart importing.  Another possible use would be to use this agent to import the subtitles only.  Since this agent will convert the language name to the language code that is required by Plex.  This would duplicate the subtitle entries, but one would show up as unknown and the other as the language name.  So... These are not major issues, but if there is no harm in the change, then it could be worth it.

**Comment by SlrG** [comment]
Okay. Why not.

I would try what happens if an old settings value was once defined (disable artwork... support) and gets now removed, by a newer version of the agent. Is it still accessible to check the value the user once set? Is it possible to change a setting from the agent? If yes, then set your new separate settings to enabled if the user had the single setting enabled. If it was disabled, all the new ones should be too.

If it's not possible to access the old setting or change them from the agent or if you don't have the time or interest to test what I described above, just define the new ones as disabled like the default for the single one was and once I have merged your changes, post in the plex forums thread explaining the change in the settings. (Sorry for the long sentence. Somehow I did not find a way to say it in a shorter way. English is not native language. :)

**Comment by sergiorbp** [comment]
Can this agent import the set/collection poster?
I'm building a Music Videos library and would like to group the videos by artists and show their profile pictures as a collection poster. The library is too big to do this manually, everything else I managed to do programmatically using AppleScript. This is the last piece of the puzzle to make it look perfect. Any advice?

**Comment by SlrG** [comment]
AFAIK this is not possible. At least it was not, the last time I tried it myself. As I stopped developing the agents however, you or someone else will have to give it a new try, to tell for sure. Pull request are welcome, if you get it running.

**Pull request merged**
