### PR TITLE
PEP 8 refactoring and various clean-up

### PR DESCRIPTION
**Pull request by labrys**
Fix `DefaultPrefs.json` by removing hanging commas.
Refactor class to `CamelCase` and functions, arguments, and variables to `snake_case`.
Compile regexes for performance and ease of editing.
Use single quoted strings and `str.format()`.
Add Plex Log Adapter to adapt log style to one similar to python standard logging.

### CODE REVIEW

**Comment by SlrG** [comment]
Is the string formatting really necessary? Makes things a bit complicated, don't you think?

**Comment by labrys** [comment]
String formatting, while not absolutely necessary adds a lot of syntactic sugar for further refactoring.
The log message itself is clearer (since it can be read straight through).
With named parameters you can change the layout of the message without having to reorder the params.
A lot of code is duplicated and can be simplified with loops, generators, etc.  The using formatting makes those refactors easier.
The format method is generally much safer with unicode coercion.
If you would like more reasons I can provide more :).

**Comment by labrys** [comment]
Also consider the case where you have the similar log messages but many conditionals to decide which to log, this can be simplified by using `.format`:
For example instead of:
```python
if not person:
    print('Hello world!'.)
```
```python
'Hello {person}!'.
```

**Comment by labrys** [comment]
Also consider the case where you have the similar log messages but many conditionals to decide which to log, this can be simplified by using `.format`:
For example instead of:
```python
if not person:
    print('Hello, world!'.)
else:
    print('Hello, '+ person + '!'
```
We would do:
```python
print('Hello, {}!'.format(person.name if person else 'world')
```
Which makes it clear that there is a single print statement which could vary based on input.

**Comment by labrys** [comment]
As an example consider the final output of the update method.
You could build a dict of the result info: `results = {'id': metadata.guid, 'title': metadata.title, ...}` and then do a final:
```python
log.info("""
    ---------------------
    Movie nfo Information
    ---------------------
    ID: {id}
    Ttitle: {title}
    ....
    ---------------------
    """.format(**results)
```
Also (assuming the attributes in metadata all exist and are all valid) you could just pass the metadata object directly and use format strings like `'ID: {metadata.guid}` without having to build a list of results.  With the broad exceptions used during those statements I'd have to look into what you're actually trying to catch to decide the method I would use.

**Pull request merged**
